# Dockerfile for Gerbera Archlinux Development
# Created by: Eamonn Buss
# Created on: 05/16/2018

##--------------------------------------
## Start with Archlinux image as the base
##--------------------------------------
FROM base/archlinux

##--------------------------------------
## Install required packages
##--------------------------------------
RUN pacman --noconfirm -Sy base-devel \
expat \
exiv2 \
sqlite3 \
mariadb \
curl \
file \
ffmpeg \
ffmpegthumbnailer \
git \
cmake \
wget

##--------------------------------------
## Setup a build user
##--------------------------------------
RUN useradd --no-create-home --shell=/bin/false build && usermod -L build
RUN echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir build
RUN chown build:build -Rv /build
WORKDIR build
USER build

##--------------------------------------
## Install Exif
##--------------------------------------
RUN git clone https://aur.archlinux.org/exif.git
WORKDIR /build/exif
RUN less PKGBUILD
RUN less exif.install
RUN makepkg -sif --noconfirm
USER root

##--------------------------------------
## Clone Gerbera GIT Repository
##--------------------------------------
RUN mkdir /build/gerbera
WORKDIR /build/gerbera
RUN git clone https://github.com/elmodaddyb/gerbera.git

RUN mkdir build
WORKDIR /build/gerbera/build

##--------------------------------------
## Install libupnp library
##--------------------------------------
RUN sh ../gerbera/scripts/install-pupnp18.sh

##--------------------------------------
## Install taglib library
##--------------------------------------
RUN sh ../gerbera/scripts/install-taglib111.sh

##--------------------------------------
## Install Duktape and make library available
##--------------------------------------
RUN sh ../gerbera/scripts/install-duktape.sh
RUN echo /usr/local/lib > /etc/ld.so.conf.d/gerbera-x86_64.conf
RUN ldconfig

##--------------------------------------
## Build & Install Gerbera
##--------------------------------------
RUN cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0
RUN make
RUN make install

##--------------------------------------
## Setup the Gerbera user
##--------------------------------------
RUN useradd --system gerbera
RUN mkdir /home/gerbera
RUN mkdir /home/gerbera/.config

RUN chown gerbera:gerbera -Rv /usr/local/share/gerbera
RUN chown gerbera:gerbera -Rv /home/gerbera
USER gerbera

ENTRYPOINT ["/usr/local/bin/gerbera"]
EXPOSE 49152/tcp 1900/udp
